// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbeqisxorvbzxcwcqjbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRiZXFpc3hvcnZienhjd2NxamJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5OTYwMzAsImV4cCI6MjA2NzU3MjAzMH0.HO6LtJEfgJwVbiTwoAVYn_GWgN1Oh458rYT-7ICBXbQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});